services:
  backend:
    build:
      context: ./backend  
    ports:
      - "8000:8000"  
    env_file:
      - .env  
    depends_on:
      - db
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000 &
               sleep 10 &&
               python automatically_start_script.py"
    
  frontend:
    build:
      context: ./frontend  
    ports:
      - "80:80"  

  ai:
    build:
      context: ./AI  
    ports:
      - "8001:8001"  
    depends_on:
      - backend
    environment:
      - FLASK_ENV=development

  db:
    image: postgres:latest 
    container_name: postgres-container 
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_DB: ${DB_NAME} 
    ports:
      - "5432:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data  

volumes:
  postgres-data: