services:
  backend:
    build:
      context: ./backend  
    ports:
      - "8000:8000"  
    env_file:
      - .env  
    environment:
      - RESET_DB=true  # Set to true if you want to reset the DB users during initialization
    depends_on:
      - db
    restart: unless-stopped
    
  frontend:
    build:
      context: ./frontend  
    ports:
      - "80:80"
    depends_on:
      - backend
      - ai
    restart: unless-stopped

  ai:
    build:
      context: ./AI  
    ports:
      - "8001:8001"  
    depends_on:
      - backend
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  db:
    image: postgres:latest 
    container_name: postgres-container 
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_DB: ${DB_NAME} 
    ports:
      - "5433:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: